# Generated by Django 5.1.6 on 2025-03-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='podcasts/thumbnails/'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='video',
            field=models.FileField(upload_to='podcasts/videos/'),
        ),
    ]
